<figure>
<img src="../Imagenes/logo-final-ap.png"  width="80" height="80" align="left"/> 
</figure>

# <span style="color:blue"><left>Aprendizaje Profundo</left></span>

# <span style="color:red"><center>Visión por Computadora</center></span>
## <span style="color:red"><center>Convolución: Definiciones</center></span>

## <span style="color:blue">Contenido</span>

## <span style="color:blue">Convolución en el calculo</span>

Empezaremos observando la convolución en su definición matemática. La "convolución" es una operación entre dos funciones

\begin{equation}
    f(t)\otimes g(t) = \int^{\infty}_{-\infty}f(t)g(t-\tau)d\tau
\end{equation}

¿Se entiende? ¿No? Busquemos un ejemplo



Imagine que está encargado de tratar varios pacientes con una misma enfermedad. Para tratar la enfermedad, un paciente necesita tres `[3]` unidades de antídoto.

Los pacientes van llegando. tenemos: Un paciente el lunes, dos el martes, tres el miercoles, cuatro el jueves y cinco el viernes. Podemos resumirlo así: `[1 2 3 4 5]`

Entonces tenemos:
- Un plan de tratamiento `[3]`, llamemos esto $f$
- Una lista de pacientes `[1 2 3 4 5]`, llamemos esto $g$

Al final del día, el hospital pide un conteo de cuantas unidades de tratamiento se aplicaron. Encontrar esto es muy sencillo. solo hay que multiplicar $f*g$ y obtenemos el conteo `[3 6 9 12 15]`. Llamemos este resultado $c$

Supongamos ahora que la enfermedad mutó y ahora el tratamiento es por múltiples días, y la dósis se va reduciendo con cada día. En este caso $f=$`[3 2 1]`. Ahora, para saber el conteo diario de unidades aplicadas tenemos que "deslizar" el tratamiento, e ir haciendo multiplicaciones.

```
Lunes:

        [3 2 1]
[5 4 3 2 1]     = 3*1 = 3

Martes:

      [3 2 1]
[5 4 3 2 1]     = 3*2 + 2*1 = 8

Miercoles:

    [3 2 1]
[5 4 3 2 1]     = 3*3 + 2*2 + 1*1 = 14

Jueves:

  [3 2 1]
[5 4 3 2 1]     = 3*4 + 2*3 + 1*2 = 20

Viernes:

[3 2 1]
[5 4 3 2 1]     = 3*5 + 2*4 + 1*3 = 26


```

agregamos también sábado y domingo por los pacientes que empezaron el viernes

```

Sábado:

[3 2 1]
  [5 4 3 2 1]     = 2*5 + 1*4 = 14

Domingo:

[3 2 1]
    [5 4 3 2 1]     = 1*5 = 5
```


Así, podemos decir que el conteo de dósis por día es igual a $c=$`[3 8 14 20 26 14 5]`

lo que acabamos de hacer fue un convolución del plan de tratamiento $f$ sobre los pacientes

podemos hacer esto más rápido usando numpy

In [1]:
import numpy as np 

f = [3, 2, 1]
g = [1, 2, 3, 4, 5]

c = np.convolve(f,g)

c2 = np.convolve(f,g, mode="valid")

print(c)
print(c2)

[ 3  8 14 20 26 14  5]
[14 20 26]


Ya que entendemos la noción matemática de convolución, podemos cambiar algunos nombres.


* El plan de tratamiento $f$ vamos a llamarlo el **Kernel**

* los pacientes a través de la semana $g$ va a ser la **Señal de Entrada**

Así que: ¿Qué es una convolución? en resumidas cuentas, es una operación donde, a partir de un **Kernel**, se obtiene información acerca de la **Señal de Entrada**.

Esto por supuesto no se acaba con listas de una dimensión. Podemos aplicar este mismo concepto en N dimensiones

In [2]:
from scipy import signal

g = np.ones((5,5))
print(g)
f = np.array([[1,2,3], #  [[6,5,4]
              [4,5,6]]) #  [3,2,1]]

c = signal.convolve2d(f,g)
c2 = signal.convolve2d(f,g, mode = "valid")

print(c)
print(c2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[ 1.  3.  6.  6.  6.  5.  3.]
 [ 5. 12. 21. 21. 21. 16.  9.]
 [ 5. 12. 21. 21. 21. 16.  9.]
 [ 5. 12. 21. 21. 21. 16.  9.]
 [ 5. 12. 21. 21. 21. 16.  9.]
 [ 4.  9. 15. 15. 15. 11.  6.]]
[[21. 21. 21.]
 [21. 21. 21.]
 [21. 21. 21.]
 [21. 21. 21.]]


## <span style="color:blue">convolución en las imagenes</span>

Se puede aplicar la convolución a cualquier tipo de dato que pueda representarse en forma de matriz. Particularmente, para nuestro interés, en las imagenes.

Las imagenes tienen componentes los cuales vamos a llamar "canales", una imagen a color puede describirse con 3 canales: Rojo, Verde y Azul. Mientras que una imágen en tono de grises solo tiene un canal. Cada uno de estos canales puede representarse como una matriz, con cada número representando un pixel de la imágen. Estos pixeles están entre 0 y 255 para representar su escala de color.

<figure>
<center>
<img src="../Imagenes/imagematrix.png" width="1000" height="400"/>
</center>
</figure>

Esta forma de representación ya sería "suficiente" para que una red neuronal entienda el concepto de imagen y la logre procesar. Pero si las imagenes son grandes, o si se trabaja con color, serían demasiados datos para que trabaje la red. No es óptimo

Aquí es donde las convoluciones brillan

<figure>
<center>
<img src="../Imagenes/convolution1.gif" width="600" height="400"/>
</center>
</figure>

Aplicamos una convolución a la imagen, de hecho podemos "resumirla".Depende de cómo definamos el kernel (el tamaño, los números dentro de este, y que tantos pasos se mueve), podemos obtener características particulares de la imagen. El resultado de la convolución se llamará un "mapa de características", y se pueden obtener varios de estos al aplicar diferentes kernel.

Se tienen los siguientes hiperparámetros que definen la salida de la convolución y el mapa de características:

- $i_j$: El tamaño de la señal de entrada en el eje $j$
- $k_j$: El tamaño del kernel en el eje $j$
- $s_j$: El "stride" o la distancia entre las posiciones del kernel en el eje $j$

## <span style="color:blue">Redes Neuronales Convolucionales</span>

¿Cómo se aplican entonces las convoluciones en una red neuronal? observemos la estructura de una CNN


### <span style="color:blue">Capa Convolucional</span>

recordemos un poco cómo funcionan los perceptrones 

<figure>
<center>
<img src="../Imagenes/perceptron.png" width="600" height="400"/>
</center>
<figcaption>Fuente: Fouzia Altaf, researchgate.net</figcaption>
</figure>

Entran datos, se hace la suma de pesos y se aplica la función de activación. Lo que hace la red en cada entrenamiento es encontrar los pesos adecuados para obtener la mejor información posible.

Es posible aplicar esta misma idea al hacer una convolución

<figure>
<center>
<img src="../Imagenes/conv_layer.png" width="800" height="400"/>
</center>
<figcaption>Fuente: Fouzia Altaf, researchgate.net</figcaption>
</figure>

Los "pesos" que busca la red van a ser ahora los elementos del kernel. Así que, ahora, en el entrenamiento, la red busca definir un kernel que le de información importante de la imagen. Ahí en adelante podemos definir el número de kernel, con cada uno haciendo una convolución diferente y, potencialmente, encontrar características separadas de la imagen.


usualmente, la capa convolucional tendrá los siguientes parámetros:

- número de canales de los datos de entrada (3 si es RGB, por ejemplo)
- número de filtros o canales de salida
- tamaño del kernel
- stride
- Padding, explicado más adelante.

### <span style="color:blue">Padding y Stride</span>

En imágenes anteriores, hemos visto que, al aplicar la convolución, el mapa de características tiene un tamaño distinto al de la imagen de entrada. 

De hecho, el tamaño del mapa de características está definido como $i_j-k_j+1$, con $j$ siendo los ejes

con esto podemos decir que, el tamaño del mapa va a depender del tamaño del kernel y los datos de entrada.

Si aplicamos varias capas convolucionales, tal vez lleguemos a perder información importante, razón por la que necesitamos métodos para mitigar estas perdidas. De igual forma tal vez querramos reducir el tamaño de forma más drástica. Aquí entra el "Padding" y el "Stride"



#### <span style="color:red">Padding</span>

En donde se pierden más pixeles es en el perímetro de la imagen. Usualmente no nos damos cuenta de esto ya que es despreciable, pero depende a los tamaños que usemos, y cuántas veces aplicamos convoluciones, la perdida puede ser más notoria. La forma de mantener los tamaños de la imagen, e incluso expandir o interpolarla, es agregando más pixeles a los bordes.

<figure>
<center>
<img src="../Imagenes/Same_padding_no_strides.gif" width="400" height="400"/>
</center>
</figure>

En el caso clásico obtendríamos un mapa tamaño $3*3$, pero al agregar una fila de pixeles de encolchamiento, mantenemos el tamaño de la imagen. reduciendo la información perdida.

Si se quiere mantener el tamaño de la imagen, se puede definir el tamaño de acolchamiento $p_j=k_j-1$. Aunque claro, no siempre se querrá mantener, sino aumentar

<figure>
<center>
<img src="../Imagenes/No_padding_no_strides_transposed.gif" width="400" height="400"/>
</center>
</figure>

¿Cómo definimos el acolchamiento? este se define en la capa convolucional. Es posible definirla usando un número, o con los strings "valid" y "same"

#### <span style="color:red">Stride</span>

Ya definimos el stride como el número de unidades que se mueve el kernel a través de los datos de entrada. 

En un caso contrario al padding, podemos definir pasos más alargados del kernel para que haga un "muestreo" de la imagen. Logrando efectivamente reducir la resolución de la imagen.

<figure>
<center>
<img src="../Imagenes/No_padding_strides.gif" width="400" height="400"/>
</center>
</figure>

¿Por qué querríamos reducir la resolución?

### <span style="color:blue">Pooling</span>

Acabamos de ver un método para reducir tamaños en las imagenes. El problema es que no es tan poderoso. 

Además, trabajando con los datos como tal, con la definición pura y altamente sensible, corremos el riesgo de que la red no logre generalizar.

Por eso es buena idea hacer una reducción de la resolución a partir de una agregación de la información. Haciendo la imagen menos detallada, pero teniendo la idea general de la información. Aquí presentamos las capas Pooling.



El proceso de pooling es de hecho bastante similar a una convolución tradicional. Se define una ventana con cierto tamaño que se ira deslizando a través de los datos de entrada. En cada paso se aplica una operación sobre la ventana de datos para generalizar ese sector. Al final se obtiene una matriz resumida de menor tamaño.

Aquí trabajamos con los mismos hiperparámetros que la capa convolucional: tamaño de la ventana, stride y padding. En este caso el stride predeterminado es del mismo tamaño que el kernel. 

¿Qué operaciones se aplican en esas ventanas?

- Max Pooling

<figure>
<center>
<img src="../Imagenes/Max_pool.png" width="1000" height="400"/>
</center>
</figure>

- Average Pooling

<figure>
<center>
<img src="../Imagenes/Avg_pool.png" width="1000" height="400"/>
</center>
</figure>

Resumamos el por qué de las capas pooling:

- Mejorar la generalización del modelo
    - El modelo aprende una representación global en lugar de cosas específicas
    - Menos susceptible a fallos si los pixeles no tienen la misa posición
- Reducir tamaños de los datos
    - Menos parametros que aprender
    - Menos operaciones computacionales

Es una buena idea agregar una capa de pooling después de una capa convolucional

### <span style="color:blue">Capa completamente conectada (FCL)</span>

A pesar de trabajar con imagenes, estas redes neuronales tienen las mismas intenciones que cualquiero otra: Clasificación, regresión, Etc. 

Así que, después de procesar las imagenes con las capas convolucionales y de pooling, necesitamos que la red aprenda la tarea con la información que obtuvo.

Esto se puede hacer, por ejemplo aplicando una o más capas "regulares" para que hagan la tarea. 

Claro, las imágenes seguirán siendo bidimensionales, razón por la cuál "Aplanamos" los datos para que puedan pasar por esta sección

<figure>
<center>
<img src="../Imagenes/flatten.png" width="800" height="400"/>
</center>
</figure>

### <span style="color:blue">CNN completa</span>

<figure>
<center>
<img src="../Imagenes/LeNet.png" width="1000" height="250"/>
</center>
</figure>

Este es el modelo clásico de una red neuronal convolucional

- Datos de entrada
- Capa Convolucional 1
- Capa de submuestreo 1(Pooling)
- Capa Convolucional 2
- Capa de submuestreo 2
- Aplanamiento
- Capa conectada 1
- Capa conectada 2
- Capa de salida